name: TuruKamar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  # done
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  permission_handler: ^11.0.1
  # testing
  http: ^1.4.0
  html: ^0.15.4
  flutter_inappwebview: ^6.0.0
  logger: ^2.5.0
  shared_preferences: ^2.0.6
  intl: ^0.18.0
  url_launcher: ^6.3.1
  provider: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  crypto: ^3.0.3

  geolocator: ^13.0.4
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.1.0
  sensors_plus: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # testing
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo_h.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/Arif.jpg
    - assets/logos/logo_h.png
